name: Deployment
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "Deploying...."
