name: Test Workflow
on: push
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/steup-node@v3
        with:
          node-version: 18
      - name: Install dpendencies
        run: npm ci
      - name: Run tests
        run: npm test
